### PR TITLE
fix custom script in travis config

### PR DESCRIPTION
**Pull request by MartinNowak**
use single entry instead of array

### CODE REVIEW

**Comment by denizzzka** [comment]
if it can help: it was broken ~18 days ago and, probably, without my help

**Comment by MartinNowak** [comment]
Figured it out, the UTF-8 BOM was the problem.

**Comment by denizzzka** [comment]
> Figured it out, the UTF-8 BOM was the problem.

Wow! I felt BOM is a good practice and set it anywhere

**Comment by denizzzka** [comment]
(fixed in another push)

Thank you very much for your help with this problem, Martin!

**Pull request closed without merging**
